### ISSUE TITLE
404 when attempting to access topics for a repo

### ISSUE THREAD

**Issue by tchupp** [github/stale-repos#51]
# Bug Report

404 when attempting to access topics for repo.

The action is able to access a number of repos, but fails out when it is unable to get topics from an unknown repo.

I don't believe this is a permissions issue, since it is able to get the age of many other repos before it fails.
Many of the repos that it was able fetch the age of have an empty topics list.

### Configuration
```
name: stale repo identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Run stale_repos tool
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.ORG_REPOS_GITHUB_TOKEN }}
        ORGANIZATION: "<org>"
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 180

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        token: ${{ secrets.GITHUB_TOKEN }}
```

### Output
```
/usr/bin/docker run --name ghcriogithubstale_reposv1_5ffdb8 --label c9a4a5 --workdir /github/workspace --rm -e "GH_TOKEN" -e "ORGANIZATION" -e "EXEMPT_TOPICS" -e "INACTIVE_DAYS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/.github/.github":"/github/workspace" ghcr.io/github/stale_repos:v1
Starting stale repo search...
Exempt topics: ['keep', 'template']
https://github.com/<org>/<omitted>: 2135 days inactive
https://github.com/<org>/<omitted>: 225 days inactive
https://github.com/<org>/<omitted>: 2495 days inactive
https://github.com/<org>/<omitted>: 1424 days inactive
https://github.com/<org>/<omitted>: 2446 days inactive
https://github.com/<org>/<omitted>: 2104 days inactive
https://github.com/<org>/<omitted>: 2339 days inactive
https://github.com/<org>/<omitted>: 1351 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1446 days inactive
https://github.com/<org>/<omitted>: 2136 days inactive
https://github.com/<org>/<omitted>: 1610 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1738 days inactive
https://github.com/<org>/<omitted>: 1658 days inactive
https://github.com/<org>/<omitted>: 2136 days inactive
https://github.com/<org>/<omitted>: 2136 days inactive
https://github.com/<org>/<omitted>: 2136 days inactive
https://github.com/<org>/<omitted>: 2123 days inactive
https://github.com/<org>/<omitted>: 2040 days inactive
https://github.com/<org>/<omitted>: 2104 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1907 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1928 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1219 days inactive
https://github.com/<org>/<omitted>: 193 days inactive
https://github.com/<org>/<omitted>: 1768 days inactive
https://github.com/<org>/<omitted>: 1696 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1708 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1282 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1348 days inactive
https://github.com/<org>/<omitted>: 1562 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 195 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 441 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1342 days inactive
https://github.com/<org>/<omitted>: 233 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 597 days inactive
https://github.com/<org>/<omitted>: 182 days inactive
https://github.com/<org>/<omitted>: 190 days inactive
https://github.com/<org>/<omitted>: 247 days inactive
https://github.com/<org>/<omitted>: 1127 days inactive
https://github.com/<org>/<omitted>: 248 days inactive
https://github.com/<org>/<omitted>: 444 days inactive
https://github.com/<org>/<omitted>: 247 days inactive

Traceback (most recent call last):
  File "/action/workspace/stale_repos.py", line 196, in <module>
    main()
  File "/action/workspace/stale_repos.py", line 52, in main
    inactive_repos = get_inactive_repos(
                     ^^^^^^^^^^^^^^^^^^^
  File "/action/workspace/stale_repos.py", line [88](https://github.com/<org>/.github/actions/runs/5626259153/job/15246705935#step:3:89), in get_inactive_repos
    topic in exempt_topics for topic in repo.topics().names
                                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github3/repos/repo.py", line 2793, in topics
    json = self._json(self._get(url, headers=self.PREVIEW_HEADERS), 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
```

**Comment by zkoppert** [comment]
Thanks for reporting this issue. I have tried to reproduce a few different ways with no luck. Have you been able to confirm that the token you used has read access to that repository or did that repo get deleted/archived?

**Comment by tchupp** [comment]
I was able to track down the repo that was causing this issue! 

I was confused on this one for a while! I ended up cloning the repo and adding some debug logging locally to figure it out.

Turns out it was a private "temporary fork" created by GitHub for a Security Advisory:
![image](https://github.com/github/stale-repos/assets/7855170/58f003f5-8974-43db-bd7d-6480aeed7ced)

Regardless, it does break this action for my org consistently. It seems that private temporary forks don't have topics 🤷🏽

**Comment by zkoppert** [comment]
Oh interesting! Thank for reporting back!
