### ISSUE TITLE
Unclear error when using the action

### ISSUE THREAD

**Issue by tfenster** [github/stale-repos#69]
When using the action, I get an error, but don't really understand what the problem is. My workflow looks like this:

```
name: stale repo identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run stale_repos tool
      uses: docker://ghcr.io/github/stale_repos:v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        INACTIVE_DAYS: 730

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        assignees: tfenster
        token: ${{ secrets.GH_TOKEN }}
```

The error message I get is

```
Run docker://ghcr.io/github/stale_repos:v1
  env:
    GH_TOKEN: ***
    ORGANIZATION: ***
    INACTIVE_DAYS: 730
/usr/bin/docker run --name ghcriogithubstale_reposv1_bb8378 --label 181ea8 --workdir /github/workspace --rm -e "GH_TOKEN" -e "ORGANIZATION" -e "INACTIVE_DAYS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/stale-repo-identifier/stale-repo-identifier":"/github/workspace" ghcr.io/github/stale_repos:v1
Starting stale repo search...
Traceback (most recent call last):
  File "/action/workspace/stale_repos.py", line [2](https://github.com/tfenster/stale-repo-identifier/actions/runs/7054897187/job/19204485701#step:4:2)29, in <module>
    main()
  File "/action/workspace/stale_repos.py", line 52, in main
    inactive_repos = get_inactive_repos(
                     ^^^^^^^^^^^^^^^^^^^
  File "/action/workspace/stale_repos.py", line 107, in get_inactive_repos
    repos = github_connection.organization(organization).repositories()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python[3](https://github.com/tfenster/stale-repo-identifier/actions/runs/7054897187/job/19204485701#step:4:3).12/site-packages/github3/github.py", line 1688, in organization
    json = self._json(self._get(url), 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: [4](https://github.com/tfenster/stale-repo-identifier/actions/runs/7054897187/job/19204485701#step:4:4)04 Not Found
```

I found #51, which also talks about a 404, but as it has a fix attached, I guess that can't be happening anymore, right?

**Comment by zkoppert** [comment]
Thanks! I'll do some testing to reproduce and trace down what is happening.

**Comment by zkoppert** [comment]
My current hypothesis: Since `github.com/tfenster` is an owner and not an organization, fetching the repos goes bonkers. I'll likely need to add code to check if its a user or organization then make the appropriate get_repo call.

**Comment by zkoppert** [comment]
Can you try dropping the `ORGANIZATION: ${{ secrets.ORGANIZATION }}` line from your workflow file? If I'm reading the code correctly, it should grab all the repos from the token creators account instead.

```python
 if organization:
        repos = github_connection.organization(organization).repositories()
    else:
        repos = github_connection.repositories(type="owner")
```

**Comment by zkoppert** [comment]
If that works, I'll switch gears to get this functionality better documented.

**Comment by tfenster** [comment]
That works, thank you!
